### ISSUE TITLE
Maybe make the throwing more like RawData?

### ISSUE THREAD

**Issue by PureDark** [ToniMacaroni/TrickSaber#10]
I mean now it feels weird to having to pull the trigger when you are supposed to throw it out.

In RawData it feels more natural by holding the trigger down, and throw the sword by releasing the trigger,

**Comment by ToniMacaroni** [comment]
you can do that by checking the 'Reverse' checkbox beside the trigger binding. You may need to adjust the threshold a little bit to make it feel more natural.
