### ISSUE TITLE
0.3.1 doesn't work with the new steam vr, 0.1.0 does

### ISSUE THREAD

**Issue by nicolasGEL** [ToniMacaroni/TrickSaber#11]
[_latest.log(0.1.0)](https://github.com/ToniMacaroni/TrickSaber/files/4725110/_latest.log)  
[_latest.log(0.3.1)](https://github.com/ToniMacaroni/TrickSaber/files/4725111/2020.06.03.18.04.31.log)

using htc vive wands,fresh mod install,and latest steam vr(3 june 2020)

[image of plugins i have in case of new incompability](https://user-images.githubusercontent.com/42648527/83669349-b7e1d500-a5d1-11ea-8903-ce2bf7cd401f.png)

**Comment by ToniMacaroni** [comment]
The issue was with AutoPauseStealth, but it got updated.
