### ISSUE TITLE
Volvo Index no functions

### ISSUE THREAD

**Issue by Master1X** [ToniMacaroni/TrickSaber#12]
Hello, I remember reading to contact you if using a Valve Index. So here I am.

No matter what I configure I got no function at all. With Oculus everything works :)

**Comment by Sventra** [comment]
Same issue on my end too, I can configure any settings of the mod but nothing works by changing any of the settings

**Comment by ToniMacaroni** [comment]
following this guide should fix it: https://www.youtube.com/watch?v=Bb4YKwmYvWk
