### ISSUE TITLE
Saber despawns and spawns again on throw and catch

### ISSUE THREAD

**Issue by Fatalution** [ToniMacaroni/TrickSaber#13]
I am using Plasma Katanas as my sabers and every time I throw them, they despawn and spawn again. This bug (is it though?) appeared after 0.3.0 update. 
The thing which bothers me is the fact that I really like those sabers and they have spawn animation with sound. So every time I throw my sabers, I am hearing the spawn sound two times - on a throw and on a catch.

Is it possible to fix this, or am I AWOL because of the sabers I use?

**Comment by ToniMacaroni** [comment]
I will look into it
