### ISSUE TITLE
Trick Saber won't allow me to release my sabers or spin?

### ISSUE THREAD

**Issue by Zarfu** [ToniMacaroni/TrickSaber#14]
Hi Toni,
I'm unsure if it's something I'm not doing correct or not however when I am in game it won't allow me to press the trigger to allow me to do tricks, like it doesn't allow me to release my sabers.
I'm currently running on a HTC Vive Cosmos Elite and whilst I'm in game it shows that TrickSaber is enabled and the config is set to my Vive triggers, sorry to be a pain but I'm just really adamant on playing with TrickSaber :0 👍

**Comment by ToniMacaroni** [comment]
hey,
can you post your "Beat Saber/Logs/_latest.log" file?
