### ISSUE TITLE
Index Issue

### ISSUE THREAD

**Issue by DianoteHD** [ToniMacaroni/TrickSaber#16]
Hello.
The Spinning with the Joystick doesn't work on my Index (with Index Controller)
Is this a mod issue or is a Controler Configuration needet to use the Joystick in BeatSaber?

Thx Dia

**Comment by ToniMacaroni** [comment]
Hi
Make sure you applied the fix in this video: https://www.youtube.com/watch?v=Bb4YKwmYvWk
