### ISSUE TITLE
custom saber issue

### ISSUE THREAD

**Issue by Haloultra** [ToniMacaroni/TrickSaber#17]
when ever i throw my saber my custom saber does not fly away a new saber spawns and mine is still in my hand.

Don't know why please help

**Comment by HelpAURA** [comment]
BMBF doesnt support .zip files anymore. You have to extract the .qsaber file and insert that into BMBF. Then start beat saber, and go into settings, and choose qosmetic settings. Then select your saber. You can change you sabers in game using this. No more must you swap using BMBF.
