### ISSUE TITLE
Sabers don't work in the new 1.13.2 update

### ISSUE THREAD

**Issue by 0Human0** [ToniMacaroni/TrickSaber#18]

**Comment by HelpAURA** [comment]
BMBF doesnt support .zip files anymore. You have to extract the .qsaber file and insert that into BMBF. Then start beat saber, and go into settings, and choose qosmetic settings. Then select your saber. You can change you sabers in game using this. No more must you swap using BMBF.

**Comment by 0Human0** [comment]
> BMBF doesnt support .zip files anymore. You have to extract the .qsaber file and insert that into BMBF. Then start beat saber, and go into settings, and choose qosmetic settings. Then select your saber. You can change you sabers in game using this. No more must you swap using BMBF.

I mean on pc
