### ISSUE TITLE
i lost my sword when i install this mod. game version is 1.13.2

### ISSUE THREAD

**Issue by chenweibin233** [ToniMacaroni/TrickSaber#19]
plz help me

**Comment by lhg8007** [comment]
same thing happend to me

**Comment by Githubbyman** [comment]
sus

**Comment by Flaffideflaff** [comment]
Same thing happened to me :/

**Comment by HelpAURA** [comment]
BMBF doesnt support .zip files anymore. You have to extract the .qsaber file and insert that into BMBF. Then start beat saber, and go into settings, and choose qosmetic settings. Then select your saber. You can change you sabers in game using this. No more must you swap using BMBF.
