### ISSUE TITLE
Saber doesnt work since the new Version

### ISSUE THREAD

**Issue by hannimew** [ToniMacaroni/TrickSaber#20]
My Saber ist just laying on the ground, i tried changing some settings but there was no solution. Bug fix would be really appreciatet! Thank you for your work on this amazing mod!

**Comment by HelpAURA** [comment]
BMBF doesnt support .zip files anymore. You have to extract the .qsaber file and insert that into BMBF. Then start beat saber, and go into settings, and choose qosmetic settings. Then select your saber. You can change you sabers in game using this. No more must you swap using BMBF.

**Comment by hannimew** [comment]
> BMBF doesnt support .zip files anymore. You have to extract the .qsaber file and insert that into BMBF. Then start beat saber, and go into settings, and choose qosmetic settings. Then select your saber. You can change you sabers in game using this. No more must you swap using BMBF.

Sorry man, i dont have a clue what that means. I dont understand much from modding and stuff. Would be so cool if Toni could create a Video for the 1.13 Vers. so everybody does understand how it works now :)
