### ISSUE TITLE
Bug on modded maps (Plus suggestion)

### ISSUE THREAD

**Issue by Sandfire5618** [ToniMacaroni/TrickSaber#22]
Either Noodle or just Mapping Extension, some notes just don't register after being sliced and just say MISS. Basically failing out of the song for no reason.

Also I do have a suggestion. When you spin the sabers, the trail stays in place as if the saber is not spinning. Not sure if you had plans on doing so but maybe have the trail follow the saber's spin movement.

**Comment by ToniMacaroni** [comment]
the trail should follow the saber, maybe try another saber.

I will investigate the notes being marked as missed issue.

**Comment by Sandfire5618** [comment]
I'm using the default sabers
