### ISSUE TITLE
Throwing a custom saber spawns another one

### ISSUE THREAD

**Issue by bubbledum** [ToniMacaroni/TrickSaber#23]
I've seen that other people have had this issue and yesterday I did not. When I first had this issue I just downloaded a new saber factory version and it worked just fine but today the glitch is happening again and idk if its a problem with my versions or a problem with some mods I have. I saw something saying a specific mod wont work with it and that mod can mess the sabers up but I don't have that mod (if it even is a mod) and I believe it was called DynamicOpenVR.BeatSaber but I only have DynamicOpenVR.

**Comment by Kali-Ember** [comment]
this was happening until I Uninstalled ModelSaber and Saber Factory using the Mod Assistant, then installing the newest release of Saber Factory from their Github that was released earlier today.
