### ISSUE TITLE
spawns in another saber

### ISSUE THREAD

**Issue by nelsonjmorris** [ToniMacaroni/TrickSaber#37]
it spawns a saber in the crotch area

**Comment by JTandT** [comment]
To add some more detail to this, the first song started after opening BeatSaber with TrickSaber installed spawns an extra red saber in the crotch area. Restarting the song gets rid of the saber and it doesn't happen again until BeatSaber is restarted.

**Comment by ToniMacaroni** [comment]
This was an issue with SiraUtil but should be resolved since version 2.5.5
