### ISSUE TITLE
FULL SUPPORT FOR 1.16.1

### ISSUE THREAD

**Issue by starvide** [ToniMacaroni/TrickSaber#40]

**Comment by starvide** [comment]
This mod Has Broken On the newest version Of beatsaber SO PLEASE fix it

**Comment by TheModdedChicken** [comment]
Hey, it's fine to want an update to a mod so you can use it in newer version of Beat Saber. But just as a friendly reminder; Toni as well as most other Beat Saber mod developers work on mods for free in their free time so please be patient with him.

The 1.16 update was just released two days ago, so as with all previous and subsequent versions of TrickSaber; Just give him time and he'll update it when he's ready to do so.

**Comment by starvide** [comment]
{The mod was updated 👍 }
