### ISSUE TITLE
Sabers Doing Tricks by Themselves

### ISSUE THREAD

**Issue by Nosuuddo** [ToniMacaroni/TrickSaber#47]
The issue: The sabers fly away / spin / vibrate my controllers right when a song starts / throughout the entire song.

What I've tried to do: I saw that DynamicOpenVR.BeatSaber was not compatible, so I removed the files, issue persisted, I did a full wipe of all mods and fresh-installed beatsaber, loaded tricksaber only along with mod assistant, issue persisted.

NOTE; Trick saber actually worked for 1 beatsaber session with mod assistant. The problem began only when I downloaded BeatSaberCustomAvatars, DynamicOpenVR / DynamicOpenVR.BeatSaber

Even after fresh wipes and installs with tricksaber as the only loaded mod, the issue persists now.

I ran through 1 song without touching my controllers at all and pulled the logs, hopefully this helps somehow;

[DEBUG @ 15:59:49 | TrickSaber/SaberTrickManager] Instantiated on LeftSaber
[DEBUG @ 15:59:49 | TrickSaber/InputManager] Started Input Manager using SteamVR
[DEBUG @ 15:59:49 | TrickSaber/SaberTrickManager] Instantiated on RightSaber
[DEBUG @ 15:59:49 | TrickSaber/InputManager] Started Input Manager using SteamVR
[INFO @ 15:59:49 | TrickSaber/SaberTrickManager] Got saber model
[DEBUG @ 15:59:49 | TrickSaber/SpinTrick] Trick: Spin initialized
[DEBUG @ 15:59:49 | TrickSaber/ThrowTrick] Trick: Throw initialized
[INFO @ 15:59:49 | TrickSaber/SaberTrickManager] 2 tricks initialized
[INFO @ 15:59:49 | TrickSaber/SaberTrickManager] Trick Manager initialized
[INFO @ 15:59:49 | TrickSaber/SaberTrickManager] Got saber model
[DEBUG @ 15:59:49 | TrickSaber/SpinTrick] Trick: Spin initialized
[DEBUG @ 15:59:49 | TrickSaber/ThrowTrick] Trick: Throw initialized
[INFO @ 15:59:49 | TrickSaber/SaberTrickManager] 2 tricks initialized
[INFO @ 15:59:49 | TrickSaber/SaberTrickManager] Trick Manager initialized

**Comment by kelvino04** [comment]
on what version of beat saber are you playing?
