### ISSUE TITLE
[Feature] keep saber hitbox to continue normally hitting notes during trick

### ISSUE THREAD

**Issue by laundmo** [ToniMacaroni/TrickSaber#5]
basically, when you do a trick like throwing the sabers, its only a visual thing, the hitboxes of the sabers stay where they are, so that you can hit blocks normally. 

this would allow for keeping my saber thrown while playing normally. it would be harder since i cant see the saber, but i wouldnt miss notes when the saber is just that close to being returned to my hand.

**Comment by GreenMan36** [comment]
+1, I hate it when it takes a little too long to return to my hand, making me miss notes.

**Comment by ToniMacaroni** [comment]
Yeah I changed it in the 0.2 update, so the hitboxes stay in place.

**Comment by laundmo** [comment]
can we reopen this issue? i just tried the 0.2 version and i cannot hit notes with the normal saber hitboxes while performing tricks
