### ISSUE TITLE
Tricksaber 1.1.2 is 1.0.0

### ISSUE THREAD

**Issue by Kouzakii** [ToniMacaroni/TrickSaber#59]
I downloaded the new updated version but when i go into my mods folder it says tricksaber 1.0.0 and it wont let me use my custom sabers but it will only let me use the original beatsaber sabers

**Comment by ToniMacaroni** [comment]
Fixed in newest version. Also Tricksaber is only compatible with Saber Factory.

**Comment by DarkGalaxy21YT** [comment]
So I am having the same issue with version 1.1.2 with saber factory installed and custom sabers when I click on trick saber it says 1.0.0 any way to fix this?
