### ISSUE TITLE
TrickSaber and bombs

### ISSUE THREAD

**Issue by GreenMan36** [ToniMacaroni/TrickSaber#6]
If you do tricks, I would suggest the spinning, your Sabers won't interact.
This will allow you to just do tricks when a few tricky bombs appear. **Allowing you to cheat.**

As suggested in #5 it should keep interactions of the Saber separate from the visuals so they'll keep working correctly. I'm not sure how hard this is or that the Sabers hit detection might be hardcoded to the model?

An alternative would be to force the tricks to collide with bombs. But this way it would still modify the gameplay and affect the scoring. Which is a no no.

**Comment by ToniMacaroni** [comment]
Hitboxes stay in place in the 0.2 update
