### ISSUE TITLE
Tricksaber 1.1.2 is 1.1.1 when I download it, also my plasma katana isnt spinning nor throwing

### ISSUE THREAD

**Issue by AidenVr22** [ToniMacaroni/TrickSaber#60]
yes, I have deleted old version and tried over and over. I also do have saber factory.

also when i throw the saber it doesnt throw the custom saber it just makes a normal beat saber saber appear and get thrown in the direction i threw.

**Comment by ToniMacaroni** [comment]
Please see if the newest version fixes your issues.

**Comment by FlorisFireball** [comment]
Is there a dll file to download? The releases last updated in December and only go up to 1.19; v1.1.2. I don't think you can download from the master, as it needs to compile to dll too, right?
