### ISSUE TITLE
Trick saber not working with Index Controller 2022

### ISSUE THREAD

**Issue by demolitiondoge** [ToniMacaroni/TrickSaber#66]
When trigger is pressed nothing happens as well as joystick, I have Saber factory and SirvaUtil 3 already downloaded. This probably has to do with the new update though I tried installing Trick Saber before ost 5 and it didn't work either which makes me very confused.

**Comment by Corrupsy** [comment]
Same issue is also happening to me. Whenever I try anything. Nothing happens.

**Comment by Blubityblub** [comment]
TL:DR, Hasn't been updated for beat saber 1.21 yet, the latest version only supports 1.19
