### ISSUE TITLE
Trick Saber just doesn't work

### ISSUE THREAD

**Issue by WanneLogan** [ToniMacaroni/TrickSaber#68]
So I don't know if it is just me, but every time I download the new version 1.1.2, in game it says it is 1.1.1 and it doesn't work at all. I have tried everything in the setting I can think of to fix it, but I am unable to do anything with the mod. And every time I go looking in on other issues the only answer that is given is, "it has been fixed." Is there something I am missing on how to fix this problem, or did something happen and the mod is just forever dead?

**Comment by lzl12051** [comment]
Same here. I am using 1.21 the latest game on Steam.  I do see settings in the main menu and the pause menu, just can't spin my saber no matter how I tried.

**Comment by Blubityblub** [comment]
The short answer is: It just hasn't been updated to 1.21 yet, if you look at the release the latest release only supports 1.19 hope that answered your question becuase it answered mine after aprox 30 mins of troubleshooting lol
