### ISSUE TITLE
About the logo

### ISSUE THREAD

**Issue by GreenMan36** [ToniMacaroni/TrickSaber#7]
Wouldn't something like this fall more inline with the Beat Saber logo style?
![image](https://user-images.githubusercontent.com/5887406/79637012-0cdd9f00-817c-11ea-80ed-7a13c55d3136.png)

If you have any way of contacting, I'd love to discuss. Since I don't have the source file this image isn't that great.

I mainly changed the font to the same a Beat Saber, adjusted it to keep the same spacing and gave the inners of the tubes including the saber the iconic white glow while the outer is still the same color.

**Comment by ToniMacaroni** [comment]
I like this attempt. You can message me on discord (Toni Macaroni#8970), so I can send you the original PSD.

**Comment by GreenMan36** [comment]
Yeah, I don't share a server with you so you'll need to accept me as a friend first.
