### ISSUE TITLE
Not working please help

### ISSUE THREAD

**Issue by RG2002** [ToniMacaroni/TrickSaber#71]
trick saber menu shows in the game but the version says it 1.0.0 and after enabling and go to game it doesn't work

**Comment by steven4547466** [comment]
Even if you build it from the current master branch it doesn't work, so you'll probably just have to wait until it's updated. Unfortunately based on the lack of response from the creator and the commit history, this project is most likely either on hold or dead until further notice. The creator might be busy or doesn't want to update it, which is fine, but it'd be cool if they archived the repo, if that's the case.
