### ISSUE TITLE
Recompiled plugins to fit new version beatsaber

### ISSUE THREAD

**Issue by blacksilvergeek** [ToniMacaroni/TrickSaber#72]
I noticed that there is no new release for this plugin.
You can download new version here.
https://github.com/blacksilvergeek/TrickSaber/releases/download/1.1.3/Plugins.zip

**Comment by KaguraXun** [comment]
1.21 or later？
不管咋样感谢

**Comment by blacksilvergeek** [comment]
> 1.21 or later？ 不管咋样感谢
我也不确定，我只是看到release里的插件不工作了，但是代码在最后一次release后还有更新，就重新编译了一次发现能工作了
I'm not sure, I just saw that the plugin in the release didn't work, but the code was updated after the last release, so I recompiled it and found that it worked

**Comment by Tutunka** [comment]
> I noticed that there is no new release for this plugin. You can download new version here. https://github.com/blacksilvergeek/TrickSaber/releases/download/1.1.3/Plugins.zip

Amazing! Works with 1.21

**Comment by einsteinfantasy** [comment]
> 
怎么重新编译能让老插件在新版本能工作 求指点
