### ISSUE TITLE
Binding multiple controls to Spin makes none of them work

### ISSUE THREAD

**Issue by zoller27osu** [ToniMacaroni/TrickSaber#8]
Bound both Grip and Thumbstick to Spin, which makes sense with Velocity Dependent on, but it doesn't trigger regardless of what I do.

**Comment by ToniMacaroni** [comment]
binding both grip and thumbstick means you have to press both at the same time to spin.
I tested it right now on SteamVR and Oculus,  and it works.

**Comment by zoller27osu** [comment]
Ah. I expected the bindings to be an Or, not an And.
Also shouldn't https://github.com/ToniMacaroni/TrickSaber/blob/ea60dce35db100743e7ba72a1ffbd24d1472f1aa/TrickSaber/Tricks/ThrowTrick.cs#L21 be based on the average/new velocity instead of the last frame's?

**Comment by ToniMacaroni** [comment]
Had it use the average velocity before, but it felt better this way.
Maybe I just used too many or too little frames for the average.
I will try it out later cause I made many other changes since I last tried it.
